### ISSUE TITLE
Variance explained by zifa factors

### ISSUE THREAD

**Issue by sidchop** [epierson9/ZIFA#11]
Hi, 
I am trying to find a principled way to select k number of factors using ZIFA. Is there a straight forward way to obtain the % of variance explained by each component/factor? 

Thank!

**Comment by epierson9** [comment]
variance explained...hm, not that I remember offhand (though it's been a while since we wrote this paper :)). but I think many standard methods you use to select the number of factors in dimensionality reduction methods should cross-apply here.
