### ISSUE TITLE
Access to x

### ISSUE THREAD

**Issue by pedrofale** [epierson9/ZIFA#9]
Would it be possible to also retrieve the entries in the expression matrix without the zeros, that is, x before passing through h?

**Comment by epierson9** [comment]
If I understand your question, the expected value of X (for the entries where Y is zero) is computed in the code in the E-step. You can change the code fairly straightforwardly to retrieve these latent expectations by, for example, returning EX at the end of the fitModel method.

**Comment by pedrofale** [comment]
Perfect. Thanks!
